# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SKY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.5'
	pod 'SwiftyJSON', '~> 3.1'
	pod 'ObjectMapper'
	pod 'AlamofireImage', '~> 3.1'
	pod 'EFInternetIndicator'
  # Pods for SKY

  target 'SKYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SKYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
